//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pubmed_Abstracttext
    {
        public int id { get; set; }
        public Nullable<int> Medlinecitation_id { get; set; }
        public string abstracttext { get; set; }
        public string label { get; set; }
        public string nlmcategory { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
