//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pubmed_author
    {
        public int id { get; set; }
        public Nullable<int> Medlinecitation_id { get; set; }
        public string authfore { get; set; }
        public string authinit { get; set; }
        public string authlast { get; set; }
        public string author { get; set; }
        public string validyn { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
