//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pubmed_Medlinecitation
    {
        public int ID { get; set; }
        public string PMID { get; set; }
        public string Title { get; set; }
        public string JournalTitle { get; set; }
        public string JournalCountry { get; set; }
        public string LinktoPubmed { get; set; }
        public string Pub_day { get; set; }
        public string Pub_month { get; set; }
        public string Pub_year { get; set; }
        public string Pubdate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
