//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubMed
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDBEntities1 : DbContext
    {
        public TestDBEntities1()
            : base("name=TestDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pubmed_Abstracttext> Pubmed_Abstracttext { get; set; }
        public virtual DbSet<Pubmed_author> Pubmed_author { get; set; }
        public virtual DbSet<Pubmed_Medlinecitation> Pubmed_Medlinecitation { get; set; }
        public virtual DbSet<Pubmed_meshheading> Pubmed_meshheading { get; set; }
    }
}
