//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_medlinecitation
    {
        public int id { get; set; }
        public Nullable<int> tb_MedlineCitationSet_id { get; set; }
        public string @abstract { get; set; }
        public string article { get; set; }
        public string articledate { get; set; }
        public string articletitle { get; set; }
        public string authorlist { get; set; }
        public string chemicallist { get; set; }
        public string citedmedium { get; set; }
        public string commentscorrectionslist { get; set; }
        public string completeyn { get; set; }
        public string copyrightinformation { get; set; }
        public string country { get; set; }
        public string databanklist { get; set; }
        public string datecompleted { get; set; }
        public string datecreated { get; set; }
        public string daterevised { get; set; }
        public string datetype { get; set; }
        public string day { get; set; }
        public string forename { get; set; }
        public string generalnote { get; set; }
        public string grantlist { get; set; }
        public string initials { get; set; }
        public string investigatorlist { get; set; }
        public string isoabbreviation { get; set; }
        public string issn { get; set; }
        public string issnlinking { get; set; }
        public string issntype { get; set; }
        public string issue { get; set; }
        public string journal { get; set; }
        public string journalissue { get; set; }
        public string keywordlist { get; set; }
        public string lastname { get; set; }
        public string medlinecitation { get; set; }
        public string medlinedate { get; set; }
        public string medlinejournalinfo { get; set; }
        public string medlinepgn { get; set; }
        public string medlineta { get; set; }
        public string meshheadinglist { get; set; }
        public string month { get; set; }
        public string nlmuniqueid { get; set; }
        public string numberofreferences { get; set; }
        public string owner { get; set; }
        public string pagination { get; set; }
        public string personalnamesubject { get; set; }
        public string personalnamesubjectlist { get; set; }
        public string pmid { get; set; }
        public string pubdate { get; set; }
        public string publicationtypelist { get; set; }
        public string pubmodel { get; set; }
        public string season { get; set; }
        public string status { get; set; }
        public string supplmeshlist { get; set; }
        public string title { get; set; }
        public string vernaculartitle { get; set; }
        public string version { get; set; }
        public string volume { get; set; }
        public string year { get; set; }
    }
}
