--SELECT column_name
--from INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES)

--SELECT TABLE_NAME 
--FROM INFORMATION_SCHEMA.TABLES
--WHERE (SELECT column_name from INFORMATION_SCHEMA.COLUMNS)

SELECT column_name,IT.TABLE_NAME 
from INFORMATION_SCHEMA.COLUMNS IC
join INFORMATION_SCHEMA.TABLES IT
ON IC.TABLE_NAME = IT.TABLE_NAME
WHERE COLUMN_NAME = 'SubCategoryID'
and IT.TABLE_NAME LIKE (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES)

SELECT * from information_schema.Tables
SELECT * from information_schema.COLUMNS